[project]
name = "claude-hooks"
version = "0.1.0"
description = "Claude Code hooks utilities"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "requests",
]

[project.optional-dependencies]
dev = [
    "pytest",
]
