[project]
name = "claude-hooks-config"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "claude-hooks",
]

[tool.uv.sources]
claude-hooks = { path = "../../src/claude-hooks", editable = true }
